<a href="https://colab.research.google.com/github/AmmarElsherif2021/AiAlgorithms/blob/master/ammar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
x=torch.empty(1)#scalar
print('scalar empty(1)',x)

x=torch.empty(3)#vector
print('vector empty(3)',x)

x=torch.empty(2,3)#matrix
print('matrix empty(2,3) ',x)

x = torch.empty(2, 2, 3) # tensor, 3 dimensions
print('tensor empty(2, 2, 3)',x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print("rand(5,3):", x)

#in zeroes
x = torch.zeros(5, 3)
print("zeros(5,3):", x)

scalar empty(1) tensor([7.4336e-35])
vector empty(3) tensor([2.5081e-37, 0.0000e+00, 7.8992e-35])
matrix empty(2,3)  tensor([[7.9060e-35, 0.0000e+00, 7.4467e-35],
        [0.0000e+00, 7.2708e+31, 5.0778e+31]])
tensor empty(2, 2, 3) tensor([[[ 7.3758e-35,  0.0000e+00,  7.4336e-35],
         [ 0.0000e+00, -1.4823e+33,  4.5771e-41]],

        [[-1.7191e+33,  4.5771e-41,  7.9091e-04],
         [ 4.5771e-41, -1.4823e+33,  4.5771e-41]]])
rand(5,3): tensor([[0.5853, 0.8451, 0.2231],
        [0.5013, 0.4004, 0.7907],
        [0.2999, 0.8515, 0.8323],
        [0.0850, 0.8675, 0.9306],
        [0.4221, 0.4992, 0.8197]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# check size
print("size", x.size())  # x.size(0)
print("shape", x.shape)  # x.shape[0]

size torch.Size([5, 3])
shape torch.Size([5, 3])


In [11]:
# check data type
print(x.dtype)
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


## Construct from data

In [12]:
# construct from data
x = torch.tensor([5.5, 3],requires_grad=True)
print(x, x.dtype)


tensor([5.5000, 3.0000], requires_grad=True) torch.float32


In [14]:
# Operations
x = torch.ones(2, 2)
y = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
z.add_(x)

print(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1602, 0.8184],
        [0.0166, 0.2027]])
tensor([[2.1602, 2.8184],
        [2.0166, 2.2027]])


In [16]:
# subtraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

print('z ',z)

z  tensor([[ 6.2421,  1.2219],
        [60.4127,  4.9332]])


In [17]:
# Slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print("x[1, 1]", x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print("x[1,1].item()", x[1,1].item())

tensor([[0.4718, 0.7415, 0.1514],
        [0.4679, 0.1034, 0.7082],
        [0.5869, 0.3537, 0.2482],
        [0.7702, 0.0092, 0.2440],
        [0.6532, 0.8861, 0.4919]])
x[:, 0] tensor([0.4718, 0.4679, 0.5869, 0.7702, 0.6532])
x[1, :] tensor([0.4679, 0.1034, 0.7082])
x[1, 1] tensor(0.1034)
x[1,1].item() 0.10342156887054443
